### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by snoopy-448** [Kevinzjy/CIRIquant#1]
Hi kevin,
Thanks for developing such a convenient package. I want to use it but I don't know how to install python. I'd appreciate it if you could give me some advice. Thanks!

**Comment by lijxug** [comment]
Hi kevin, 
Great tool, can't wait to see your article online. 
I just have one question about your tool. What's python and how to install it.
Many thanks.

**Comment by Kevinzjy** [comment]
Please refer to [https://www.anaconda.com/distribution/#download-section](https://www.anaconda.com/distribution/#download-section) and download the python 2.7 version.

**Comment by snoopy-448** [comment]
Hi lijxug,
Python is a programming language. It's simple and easy to learn.
