### ISSUE TITLE
Biologist Suggestion: Text Summary Tables

### ISSUE THREAD

**Issue by DarioS** [Kevinzjy/CIRIquant#10]
My biologist collaborator had a suggestion which I thought I would describe because it might be useful to be a utility in CIRIquant. Currently, the final results are available in GTF format, one file per sample, which requires programming skills to parse. Might a utility be added which takes as input a folder and imports all files with GTF suffix and outputs a table of BSJ counts and another table containing junction ratios? It would make it quick and easy for the biologist to open the TSV or CSV file in a spreadsheet and sort and filter results with software they are familiar with.

**Comment by Kevinzjy** [comment]
The `prep_CIRIquant` command can convert GTF outputs from multiple samples to CSV file, please refer to https://ciriquant-cookbook.readthedocs.io/en/latest/de.html#study-with-biological-replicates

**Comment by DarioS** [comment]
Ah, that's what I need! I am treating my sample pairs as unreplicated, because I believe the change won't be in many patients and I want to identify large changes, even if only present in one patient, so I didn't read that section.
