### ISSUE TITLE
--RNaseR: command not found 

### ISSUE THREAD

**Issue by hernerrrrr** [Kevinzjy/CIRIquant#14]
When trying to run Step 2 on total RNA to calculate RNase R efficiency, the mapping/circRNA detection completes, but it says that the command for RNase R is not found (--RNaseR: command not found ) in the error file. There is no extra header information pertaining to RNase R treatment in any outfile. I used the exact same format for the command as listed on the documentation, while inputting my .gtf from the RNase R treated sample. 
![Screen Shot 2020-08-13 at 12 25 46 PM](https://user-images.githubusercontent.com/69643004/90160716-24124f00-dd60-11ea-9b14-2d84d3f32798.png)

**Comment by Kevinzjy** [comment]
Hi @hernerrrrr , could you show me the content in your submitted batch file?
