### ISSUE TITLE
index not built

### ISSUE THREAD

**Issue by stfacc** [Kevinzjy/CIRIquant#15]
Running CIRIquant for circRNA quantification I obtain the error shown at the end of the attached log file.

It seems that the index is not built for some reason.
[CAN_FCX.log](https://github.com/Kevinzjy/CIRIquant/files/5202228/CAN_FCX.log)

**Comment by Kevinzjy** [comment]
Hi @stfacc , could you show me the content in /data/kronos/sfacchini/rnaseq/circrna/CAN_FCX/circ/CAN_FCX_index.ciri and /data/kronos/sfacchini/rnaseq/circrna/CAN_FCX/CIRIerror.log ? It seems that CIRI2 failed to detect circRNAs from your data.

**Comment by stfacc** [comment]
CAN_FCX_index.ciri does not exist, there are instead CAN_FCX.ciri and CAN_FCX_index.fa: both files are empty.
CIRIerror.log is also empty.

I saw in the main log that the phase `[Thu 2020-09-10 14:40:12] [INFO ] Extract circular sequence` begins _before_ all 64 threads completed the previous phase.

I tried reducing the number of threads to 16 and it worked fine.

**Comment by Kevinzjy** [comment]
Thanks for the feedback. By the way, running CIRI2 using multi-thread will require a large amounts of RAM, and we do not recommend to use more than 20 threads under any circumstances.

**Comment by cjs0617** [comment]
Hi Kevin,

I had the same problem, but I don't know what "reducing the number of threads" mean. Can you elaborate on that? Or it there another way to solve this problem?

Also it's weird. When I was running the test data as a batch file, the run was terminated due to this error. Then I immediately ran the test data in the command line, and I got the desired output in only 2-3 minutes. However, when I ran the experimental data today, running it as a batch file or in the command line both gave this same error. Do you know why does it happen?

**Comment by algaebrown** [comment]
I experience a similar problem with 16 threads
```
[Fri 2022-05-27 18:36:29] [INFO ] Extract circular sequence
[Fri 2022-05-27 18:36:29] [INFO ] Building circular index ..
Settings:
  Output files: "/oasis/tscc/scratch/hsher/circSTAMP_pipe/output/circ/APO-noD-R_index.*.ht2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Local offset rate: 3 (one in 8)
  Local fTable chars: 6
  Local sequence length: 57344
  Local sequence overlap between two consecutive indexes: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  /oasis/tscc/scratch/hsher/circSTAMP_pipe/output/circ/APO-noD-R_index.fa
Warning: Empty fasta file: '/oasis/tscc/scratch/hsher/circSTAMP_pipe/output/circ/APO-noD-R_index.fa'
Warning: All fasta inputs were empty
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal HISAT2 exception (#1)
Command: hisat2-build --wrapper basic-0 -p 16 -f /oasis/tscc/scratch/hsher/circSTAMP_pipe/output/circ/APO-noD-R_index.fa /oasis/tscc/scratch/hsher/circSTAMP_pipe/output/circ/APO-noD-R_index 
[Fri 2022-05-27 18:36:38] [INFO ] De novo alignment for circular RNAs ..
(ERR): "/oasis/tscc/scratch/hsher/circSTAMP_pipe/output/circ/APO-noD-R_index" does not exist
Exiting now ...
```
