### ISSUE TITLE
Rowname error with CIRI_DE_replicate command

### ISSUE THREAD

**Issue by prisca399** [Kevinzjy/CIRIquant#23]
Hi @Kevinzjy,

I am trying to execute the CIRI_DE_replicate command but I keep on getting the following error:

Error in `[.data.frame`(gene_mtx, , rownames(lib_mtx)) : 
  undefined columns selected
Calls: [ -> [.data.frame
Execution halted
[Sat 2021-03-06 12:08:08] [INFO ] Finished!

I think the error means that it cannot match the sample names listed in library_info.csv to the sample names in gene_count_matrix.csv. I have checked to verify that the sample naming in both files is the same, and the individual line responsible for subsetting in your CIRI_DE.R script  (gene_mtx <- gene_mtx[,rownames(lib_mtx)]) works just as expected when run in isolation on the same data sets. Would you have any insight into why the line is throwing an error in the context of your script? I suspect something may be off with my environment set-up, but I really have no clue.

Thank you!  Certainly let me know if you would need any more information to answer my question.

Prisca

**Comment by prisca399** [comment]
Hi @Kevinzjy, 

I was able to resolve this error. I noticed that an edit was added by @osagiei to the CIRI_DE.R file recently that would accommodate reading in of sample_IDs starting with a number. By git-cloning the most updated version of CIRIquant that included this edit, I was able to complete the differential expression successfully. Thanks!

**Comment by Kevinzjy** [comment]
Thanks, I will update the releases page soon.
