### ISSUE TITLE
Add support for strand specific RNA-seq data

### ISSUE THREAD

**Issue by Kevinzjy** [Kevinzjy/CIRIquant#3]

**Comment by DarioS** [comment]
Stranded protocol is more common these days than unstranded protocol, so I hope you add it soon.

**Comment by Kevinzjy** [comment]
Hi @DarioS , I added the options for stranded library in the new *beta* branch, but I don't have any stranded RNA-seq data at hand. Could you try this version on your data to see how it's working?

**Comment by Kevinzjy** [comment]
Also fixed #7 #8

**Comment by DarioS** [comment]
I don't know what to look for in the results to judge if they are good or bad. ENCODE Project has many freely available strand-specific RNA sequencing files to download. You could try using [GM12878 R1](https://www.encodeproject.org/files/ENCFF001RFH/) and [GM12878 R2](https://www.encodeproject.org/files/ENCFF001RFG/) FASTQ files. You can click the purple Download button on the webpage to get a FASTQ file.

**Comment by Kevinzjy** [comment]
Thanks, I'm testing on it.

**Comment by Kevinzjy** [comment]
Hi @DarioS , support for stranded library and GFF3 format annotation was added in the latest version 1.1 .

**Comment by Kevinzjy** [comment]
#9
