### ISSUE TITLE
Cannot serialize a string larger than 2 GB

### ISSUE THREAD

**Issue by solo7773** [Kevinzjy/CIRIquant#6]
I encounter this error. I hope you can help to solve it. Many thanks.

![image](https://user-images.githubusercontent.com/3683770/75789856-4d888100-5da5-11ea-80bb-7aaf05c2905e.png)

The last line of the above figure shows the reads in the input file.

![image](https://user-images.githubusercontent.com/3683770/75789869-54af8f00-5da5-11ea-87c2-8b8f1f3817c5.png)

**Comment by Kevinzjy** [comment]
Hi solo7773, you could try our latest release [v1.0.1](https://github.com/Kevinzjy/CIRIquant/releases/download/v1.0.1/CIRIquant_v1.0.1.tar.gz). I believe this problem has been solved.
