### ISSUE TITLE
More Precise Definition of Options

### ISSUE THREAD

**Issue by DarioS** [Kevinzjy/CIRIquant#7]
I was reading the user guide and I saw that `--tool` is described as "User provided tool name for circRNA prediction" and I was wondering if this was any name the user would like to use to refer to the tool or if there are a limited set of valid values. I found the answer to my uncertainty by reading the source code and noticing:

```python
TOOLS = ['CIRI2']
if tool not in TOOLS:
```

This information should be in the user guide and any other parameter which has a restricted set of allowed values should show all of the allowed values in the user guide. I also wonder if there could be a vignette showing the use of CIRI2, CIRIquant and CIRI-vis, to show users a full end-to-end workflow. For example, [maftools has a nice vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html) showing all of its major features using a built-in AML data set.

**Comment by Kevinzjy** [comment]
Thanks for the advice, I'm planning to add support for circRNAs predicted from other widely used tools:
 e.g. CIRCexplorer2 / find_circ / KNIFE,  and I will update detailed information about --circ and --tool in the same time.

**Comment by DarioS** [comment]
`--circ` and `--tool` are optional. Is there any benefit to running CIRI2 first, or should I save time and start from CIRIquant? I notice that CIRIquant has the same input as CIRI2 - a pair of trimmed reads files. Is running CIRI2 before CIRIquant recommended or does CIRIquant completely replace CIRI2?

Also, I noticed a typing mistake; `-o, -out` should be `-o, --out` (two dashes for word) in README file.

**Comment by Kevinzjy** [comment]
CIRIquant include a copy of CIRI2 program to predict circRNAs when `--circ` and `--tool` options are not provided, so you won't need to manually run CIRI2 anymore.
