### ISSUE TITLE
CIRI2 Missing FIle Error

### ISSUE THREAD

**Issue by DarioS** [Kevinzjy/CIRIquant#9]
I am running CIRIquant without CIRI2 results files, so it is doing the analysis within the pipeline. The first couple of steps seem to work fine, but CIRI2 analysis fails with an error about a missing file.

```
[Mon 2020-04-13 17:28:53] [INFO ] Input reads: CSCC_0002-M1_R1.fastq.gz,CSCC_0002-M1_R2.fastq.gz
[Mon 2020-04-13 17:28:53] [INFO ] Output directory: /dskh/nobackup/biostat/datasets/HeadNeckCancer/RNAseq/CSCC/circular, Output prefix: CSCC_0002-M1
[Mon 2020-04-13 17:28:53] [INFO ] Config: hg38 Loaded
[Mon 2020-04-13 17:28:53] [INFO ] 32 CPU cores availble, using 12
[Mon 2020-04-13 17:28:53] [INFO ] Align RNA-seq reads to reference genome ..
[Mon 2020-04-13 18:04:24] [INFO ] Estimate gene abundance ..
[Mon 2020-04-13 18:16:52] [INFO ] No circRNA information provided, run CIRI2 for junction site prediction ..
[Mon 2020-04-13 18:16:52] [INFO ] Running BWA-mem mapping candidate reads ..
[Mon 2020-04-13 19:48:59] [INFO ] Running CIRI2 for circRNA detection ..
Traceback (most recent call last):
  File "/dskh/nobackup/biostat/software/PythonLegacy/bin/CIRIquant", line 11, in <module>
    load_entry_point('CIRIquant==1.0.2', 'console_scripts', 'CIRIquant')()
  File "/dskh/nobackup/biostat/software/PythonLegacy/local/lib/python2.7/site-packages/CIRIquant-1.0.2-py2.7.egg/CIRIquant/main.py", line 156, in main
    circ_parser.convert(bed_file)
  File "/dskh/nobackup/biostat/software/PythonLegacy/local/lib/python2.7/site-packages/CIRIquant-1.0.2-py2.7.egg/CIRIquant/utils.py", line 155, in convert
    circ_data = getattr(self, '_' + self.tool.lower())()
  File "/dskh/nobackup/biostat/software/PythonLegacy/local/lib/python2.7/site-packages/CIRIquant-1.0.2-py2.7.egg/CIRIquant/utils.py", line 146, in _ciri2
    with open(self.circ, 'r') as f:
IOError: [Errno 2] No such file or directory: '/dskh/nobackup/biostat/datasets/HeadNeckCancer/RNAseq/CSCC/circular/circ/CSCC_0002-M1.ciri'[Mon 2020-04-13 17:28:53] [INFO ]
```

What is wrong and can the error be caught (try-catch) and an informative message printed in future?

**Comment by Kevinzjy** [comment]
What's the content of /dskh/nobackup/biostat/datasets/HeadNeckCancer/RNAseq/CSCC/circular/CSCC_0002-M1.log ?

**Comment by DarioS** [comment]
Interesting. The last two lines in the logging file are:

> The GFF file provided cannot be understood by CIRI! Please refer to manual for details of required GFF formats
> Fatal error. Aborted.

My YAML file has:

```
gtf: /savona/nobackup/biostat/databases/GRCh38/gencode.v31.annotation.sorted.gff3
```

It has been sorted by igvtools because IGV insists the file be sorted before it is loaded for viewing. Does CIRI support files downloaded from GENCODE Genes?

**Comment by Kevinzjy** [comment]
Yes, CIRI should support annotation in both gtf and gff3 format. The unsorted main annotation file from GENCODE in either GTF/GFF3 format should do the job.

**Comment by DarioS** [comment]
I tested using original GENCODE GFF3 and GTF files. It fails with GFF3 but works well with GTF. Can you reproduce the problem on your computer using [GENCODE Genes](https://www.gencodegenes.org/human/) and improve CIRI2's GFF3 support?

**Comment by Kevinzjy** [comment]
Fixed in [beta](https://github.com/Kevinzjy/CIRIquant/tree/beta) branch.
